Repository xEdziu/KeepMyPassword-Desktop, pull requests merged in 2022-10, with the labels that each got.

#103 Readable languages
  linux-install.sh
  pom.xml
  src/main/java/me/goral/keepmypassworddesktop/controllers/MainAppController.java
  src/main/java/me/goral/keepmypassworddesktop/util/AlertsUtil.java
  src/main/java/me/goral/keepmypassworddesktop/util/LanguageConverter.java
  src/main/resources/language_it-it.properties
Labels: enhancement, translation, hacktoberfest-accepted

#102 Improved style for TextField, CheckBox and ComboBox
  src/main/resources/me/goral/keepmypassworddesktop/styles/dialog.css
Labels: enhancement, hacktoberfest-accepted

#86 Spelling improved, spelling errors fixed.
  src/main/resources/language_de-de.properties
Labels: translation, hacktoberfest-accepted

#87 update indonesian language
  src/main/resources/language_in-id.properties
Labels: translation, hacktoberfest-accepted

#89 Added Turkish translation
  src/main/resources/language_tr-tr.properties
Labels: translation, hacktoberfest-accepted

#90 Added gujarati-english translation
  src/main/resources/language_gu-in.properties
Labels: translation, hacktoberfest-accepted

#91 Update Hindi language_hi-in.properties
  src/main/resources/language_hi-in.properties
Labels: translation, hacktoberfest-accepted

#94 Add traditional Chinese (zh-hk) translations
  src/main/resources/language_zh-hk.properties
Labels: translation, hacktoberfest-accepted

#100 Added Amharic Translation file
  src/main/resources/langauge_single-am.properties
Labels: translation, hacktoberfest-accepted

#98 Add marathi-english translation
  src/main/resources/language_ma-in.properties
Labels: translation, hacktoberfest-accepted

#96 Translate to Bengali.
  src/main/resources/language_bn-bn.properties
Labels: translation, hacktoberfest-accepted

#99 Improved german once more and rephrased some english entries
  src/main/resources/language_de-de.properties
  src/main/resources/language_en-us.properties
Labels: translation, hacktoberfest-accepted

#104 Add traditional Chinese (zh-tw) translation
  src/main/resources/language_zh-tw.properties
Labels: translation, hacktoberfest-accepted

#105 [Refactor: Adding dutch language]
  src/main/resources/language_nl-nl.properties
Labels: translation, hacktoberfest-accepted

#109 AESUtil tests introduced
  src/test/java/keepmypassworddesktop/util/AESUtilTest.java
Labels: enhancement, hacktoberfest-accepted

#110 Update Romanian translation
  src/main/resources/language_ro-ro.properties
Labels: translation, hacktoberfest-accepted

#95 Improve german translation
  src/main/resources/language_de-de.properties
Labels: translation, hacktoberfest-accepted

#101 Create language_it-it.properties
  src/main/resources/language_it-it.properties
Labels: translation, hacktoberfest-accepted

#112 Create language_vi-vn.properties
  src/main/resources/language_vi-VN.properties
Labels: translation, hacktoberfest-accepted

#113 Added support for Bosnian Latin language (sr-Latn-BA)
  src/main/resources/language_sr-latn-ba.properties
Labels: translation, hacktoberfest-accepted

#114 Added support for the Nepali language, And Improved Hindi translation.
  src/main/resources/language_hi-in.properties
  src/main/resources/language_np-np.properties
Labels: translation, hacktoberfest-accepted

#115 Added Hebrew Language
  src/main/resources/me/language_iw-il.properties
Labels: translation, hacktoberfest-accepted

#116 Updated language_hi-in.properties
  src/main/resources/language_hi-in.properties
Labels: translation, hacktoberfest-accepted

#117 added marathi language translation
  src/main/resources/langauge_mr-in.properties
Labels: translation, hacktoberfest-accepted

#118 added telugu language translations
  src/main/resources/language_es-te.properties
Labels: translation, hacktoberfest-accepted

#119 added tamil language
  src/main/resources/language_es-ta.properties
Labels: translation, hacktoberfest-accepted

#120 Update language_in-id.properties
  src/main/resources/language_in-id.properties
Labels: translation, hacktoberfest-accepted

#122 Added Danish Language
  src/main/resources/language_da-dk.properties
Labels: translation, hacktoberfest-accepted

#123 Added translation for brazilian portuguese
  src/main/resources/language_pt-br.properties
Labels: translation, hacktoberfest-accepted

#121 Create language_lv-lv.properties
  src/main/resources/language_lv-lv.properties
Labels: translation, hacktoberfest-accepted

#125 Create language_ur-pk.properties
  src/main/resources/language_ur-pk.properties
Labels: translation, hacktoberfest-accepted

#126 Corrects some mistakes in the french translation
  src/main/resources/language_fr-fr.properties
Labels: translation, hacktoberfest-accepted

#124 corrected file name typo
  src/main/resources/language_mr-in.properties
  src/main/resources/language_single-am.properties
  src/main/resources/language_ta-in.properties
  src/main/resources/language_te-in.properties
Labels: translation, hacktoberfest-accepted

#133 Grammatical Updates in the Readme file
  README.md
Labels: documentation, hacktoberfest-accepted

#138 Added Irish language Translations
  src/main/java/me/goral/keepmypassworddesktop/util/LanguageConverter.java
  src/main/resources/language_ga-ie.properties
Labels: translation, hacktoberfest-accepted

#131 Add Finnish translation
  src/main/resources/language_fi-fi.properties
Labels: translation, hacktoberfest-accepted

#136 updated tamil translation
  src/main/resources/language_ta-in.Properties
Labels: translation, hacktoberfest-accepted

#135 Added Russian translation
  src/main/resources/langugage_ru-ru.properties
Labels: translation, hacktoberfest-accepted

#137 Added a Mandarin chinese translation
  src/main/resources/language_zh-cn.properties
Labels: translation, hacktoberfest-accepted

#141 Create language_mal-in.properties
  src/main/resources/language_mal-in.properties
Labels: translation, hacktoberfest-accepted

#143 Added Konkani Translations
  src/main/resources/language_ko-in.properties
Labels: translation, hacktoberfest-accepted

#144 Create language_sv-se.properties
  src/main/resources/language_sv-se.properties
Labels: translation, hacktoberfest-accepted

#145 Create language_bh-in.properties
  src/main/resources/language_bh-in.properties
Labels: translation, hacktoberfest-accepted

#146 minor changes to fr translations
  src/main/resources/language_fr-fr.properties
Labels: translation, hacktoberfest-accepted

#142 Create language_pu-in.properties
  src/main/resources/language_pu-in.properties
Labels: translation, hacktoberfest-accepted
